task: "docvqa_val"
test_split: validation
process_results: !function utils.docvqa_process_results
metric_list:
  - metric: anls
    aggregation: mean
    higher_is_better: true
include: _default_template_docvqa_yaml
