task: "infovqa_val"
test_split: validation
output_type: generate_until
process_results: !function utils.infovqa_process_results
metric_list:
  - metric: anls
    aggregation: mean
    higher_is_better: true
include: _default_template_infovqa_yaml